version: '3'

services:
  booking:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminc70c051cc-832f
      POSTGRES_DB: bookingdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: cms-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - booking
    volumes:
      - .:/app

volumes:
  pgdata: {}
